// Import Assets
import Ethernaut from "../assets/Ethernaut.png";
import sentiment from "../assets/sentiment.png";
import krypt from "../assets/krypt.png";
import defi from "../assets/defi.png";
import ainft from "../assets/ai-nft.png";
import sol from "../assets/sol.png";

const Projects = () => {
  return (
    <section className="projects">
      <h2>My Projects</h2>

      <div className="projects__cards">
        <div className="projects__card">
          <h3>Ethernaut</h3>
          <img src={Ethernaut} alt="Ethernaut" />
          <p>
            Smart-contract Security & Auditing. 13 Levels with 13 different
            security vulnerability SOLVED. With detailed explaination and key
            takeaways.
          </p>
          <a
            href="https://github.com/gaurav-11018/Ethernaut"
            target="_blank"
            className="button"
          >
            Code
          </a>
        </div>

        <div className="projects__card">
          <h3>Sentiment</h3>
          <img src={sentiment} alt="sentiment Landing Page" />
          <p>
            Sentiment Web3 Dapp which allows u to vote if the token goes up or
            down. Vote ur sentiment and let the world know how u feel abt the
            token.
          </p>

          <a
            href="https://sentiment-web3dapp.gaurav-11018.repl.co/"
            target="_blank"
            className="button"
          >
            Site
          </a>
          <a
            href="https://github.com/gaurav-11018/Sentiment-WEB3_DAPP"
            target="_blank"
            className="button"
          >
            Code
          </a>
        </div>

        <div className="projects__card">
          <h3>Krypt</h3>
          <img src={krypt} alt="krypt Landing Page" />
          <p>
            Krypt-Web3-Dapp Send crypto to whoever you want with just a click.
            Tools used in this project: Hardhat+Solidity✅ React✅ Alchemy✅
          </p>
          <a
            href="https://github.com/krypt/krypt-v3-core"
            target="_blank"
            className="button"
          >
            Code
          </a>
        </div>

        <div className="projects__card">
          <h3>DEFI</h3>
          <img src={defi} alt="defi Landing Page" />
          <p>
            Decentralized-Finance.This project Depositing ETH, and gain interest
            on the principal. Borrowing DAI.Approve the amount that can be
            borrowed calculating the risk factor. Defi-Tools used:Aave
            Protocol,Uniswap.
          </p>
          <a
            href="https://github.com/gaurav-11018/DEFI"
            target="_blank"
            className="button"
          >
            Code
          </a>
        </div>

        <div className="projects__card">
          <h3>AI-NFT</h3>
          <img src={ainft} alt="NFT Page" />
          <p>
            AI-NFT. NFT collection is Generated by AI with DALLE. The NFT
            contract is a normal ERC721.
          </p>
          <a
            href="https://github.com/gaurav-11018/AI-NFT"
            target="_blank"
            className="button"
          >
            Code
          </a>
        </div>

        <div className="projects__card">
          <h3>Solidity-Basics</h3>
          <img src={sol} alt="Landing Page" />
          <p>
            Solidity Basics .Here are few very basic programs coded in Solidity.
            All of them are self-explanatory programs.
          </p>
          <a
            href="https://github.com/gaurav-11018/solidity_basics"
            target="_blank"
            className="button"
          >
            Code
          </a>
        </div>
      </div>
    </section>
  );
};

export default Projects;
